In [ ]:
import pandas as pd
df = pd.read_csv('df_final.csv')
df.head()

# MERCHANT_STATE 기준 분석

In [ ]:
state_to_region = {
    # 동북부 (Northeast)
    'CT': 'Northeast', 'ME': 'Northeast', 'MA': 'Northeast', 'NH': 'Northeast', 'RI': 'Northeast', 'VT': 'Northeast', 'NJ': 'Northeast', 'NY': 'Northeast', 'PA': 'Northeast',
    # 중서부 (Midwest)
    'IL': 'Midwest', 'IN': 'Midwest', 'MI': 'Midwest', 'OH': 'Midwest', 'WI': 'Midwest', 'IA': 'Midwest', 'KS': 'Midwest', 'MN': 'Midwest', 'MO': 'Midwest', 'NE': 'Midwest', 'ND': 'Midwest', 'SD': 'Midwest',
    # 남부 (South)
    'DE': 'South', 'FL': 'South', 'GA': 'South', 'MD': 'South', 'NC': 'South', 'SC': 'South', 'VA': 'South', 'DC': 'South', 'WV': 'South', 'AL': 'South', 'KY': 'South', 'MS': 'South', 'TN': 'South', 'AR': 'South', 'LA': 'South', 'OK': 'South', 'TX': 'South',
    # 서부 (West)
    'AZ': 'West', 'CO': 'West', 'ID': 'West', 'MT': 'West', 'NV': 'West', 'NM': 'West', 'UT': 'West', 'WY': 'West', 'AK': 'West', 'CA': 'West', 'HI': 'West', 'OR': 'West', 'WA': 'West'
}

# 가맹점 위치(MERCHANT_STATE) 기준으로 REGION 칼럼 추가
df['REGION'] = df['MERCHANT_STATE'].map(state_to_region).fillna('Unknown')

In [ ]:
import pandas as pd

# 데이터프레임 이름이 'df'라고 가정합니다.
# 결측치나 공백 제거 등 기본 전처리가 되어있다고 가정합니다.

# ==========================================
# 1. 지역별 업종(카테고리) 소비 비중 비교
# ==========================================
# 각 지역 내에서 특정 카테고리가 차지하는 비중(%)을 계산합니다.
category_ratio = pd.crosstab(
    index=df['MERCHANT_CATEGORY_LEVEL_3'], 
    columns=df['REGION'], 
    normalize='columns' # 열(지역) 기준으로 100%가 되도록 정규화
) * 100

# 보기 편하게 소수점 둘째 자리까지 반올림
category_ratio = category_ratio.round(2)

print("--- 지역별 업종 비중(%) ---")
display(category_ratio)


# ==========================================
# 2. 지역별 가맹점 이름 소비 비중 비교 (전체)
# ==========================================
merchant_ratio = pd.crosstab(
    index=df['MERCHANT_NAME'], 
    columns=df['REGION'], 
    normalize='columns'
) * 100

merchant_ratio = merchant_ratio.round(2)


# ==========================================
# 3. [추천] 각 지역별 TOP 10 가맹점 비중 추출
# ==========================================
# 전체 가맹점을 보면 표가 너무 길어지므로, 지역별로 가장 많이 소비한 TOP 10만 뽑아냅니다.
def get_top_merchants(group, top_n=10):
    # 그룹(지역) 내 비중 계산
    ratios = group.value_counts(normalize=True) * 100
    # 상위 N개 반환
    return ratios.nlargest(top_n).round(2)

# REGION으로 그룹화한 뒤 MERCHANT_NAME 단위로 함수 적용
top_merchants_by_region = df.groupby('REGION')['MERCHANT_NAME'].apply(get_top_merchants)

# 결과를 데이터프레임 형태로 깔끔하게 변환
top_merchants_df = top_merchants_by_region.reset_index()
top_merchants_df.columns = ['REGION', 'MERCHANT_NAME', 'RATIO(%)']

print("\n--- 지역별 TOP 10 가맹점 비중(%) ---")
display(top_merchants_df)

--- 지역별 업종 비중(%) ---

REGION                              Midwest  Northeast  South  Unknown  West
MERCHANT_CATEGORY_LEVEL_3
Airline Travel                         0.02       0.03   0.02     0.05  0.06
American Restaurants                   6.13       2.85   3.75     5.73  3.02
Amusement Parks                        0.09       0.20   0.29     0.37  0.29
Apparel, Accessories, and Footwear     0.00       0.00   0.00     0.01  0.01
Arcades                                0.00       0.00   0.00     0.00  0.00
...                                     ...        ...    ...      ...   ...
Upscale Hotels                         0.00       0.00   0.00     0.00  0.00
Vending & Beverage Retailers          14.16      10.23  11.68     8.33  9.13
Video Game Retail and Streaming        0.00       0.00   0.00     0.00  0.00
Wireless Services                      0.00       0.00   0.00     0.00  0.00
Women's Apparel                        0.00       0.00   0.00     0.00  0.01

[87 rows x 5 columns]

--- 지역별 TOP 10 가맹점 비중(%) ---

       REGION       MERCHANT_NAME  RATIO(%)
0     Midwest           MCDONALDS     18.55
1     Midwest           NO ENTITY     18.33
2     Midwest           STARBUCKS      5.34
3     Midwest  365 RETAIL MARKETS      4.95
4     Midwest           TACO BELL      4.81
5     Midwest              WENDYS      3.69
6     Midwest       DUNKIN DONUTS      3.15
7     Midwest         BURGER KING      3.05
8     Midwest         CHICK-FIL-A      2.60
9     Midwest            CHIPOTLE      2.49
10  Northeast           NO ENTITY     24.29
11  Northeast           MCDONALDS     15.45
12  Northeast       DUNKIN DONUTS     14.81
13  Northeast           STARBUCKS      6.24
14  Northeast              WENDYS      3.81
15  Northeast         BURGER KING      3.72
16  Northeast         CHICK-FIL-A      3.09
17  Northeast  365 RETAIL MARKETS      2.99
18  Northeast           TACO BELL      2.35
19  Northeast            CHIPOTLE      2.31
20      South           NO ENTITY     19.45
21      South           MCDONALDS     14.56
22      South         CHICK-FIL-A      7.33
23      South           STARBUCKS      5.36
24      South  365 RETAIL MARKETS      4.03
25      South           TACO BELL      3.27
26      South              WENDYS      3.21
27      South       DUNKIN DONUTS      2.75
28      South      SONIC DRIVE-IN      2.64
29      South         BURGER KING      2.57
30    Unknown           NO ENTITY     30.55
31    Unknown           MCDONALDS     12.99
32    Unknown           STARBUCKS      5.18
33    Unknown         BURGER KING      4.67
34    Unknown              WENDYS      4.67
35    Unknown         CHICK-FIL-A      3.32
36    Unknown           TACO BELL      2.71
37    Unknown              SUBWAY      2.65
38    Unknown  365 RETAIL MARKETS      2.42
39    Unknown     CHURCHS CHICKEN      2.05
40       West           NO ENTITY     27.59
41       West           MCDONALDS     13.95
42       West           STARBUCKS      9.47
43       West           TACO BELL      3.66
44       West         CHICK-FIL-A      3.09
45       West              WENDYS      2.66
46       West  DUTCH BROS. COFFEE      2.41
47       West     JACK IN THE BOX      2.35
48       West       PANDA EXPRESS      2.17
49       West  365 RETAIL MARKETS      2.04

# CARD_HOLDER_STATE 기준 분석

In [ ]:
state_to_region = {
    # 동북부 (Northeast)
    'CT': 'Northeast', 'ME': 'Northeast', 'MA': 'Northeast', 'NH': 'Northeast', 'RI': 'Northeast', 'VT': 'Northeast', 'NJ': 'Northeast', 'NY': 'Northeast', 'PA': 'Northeast',
    # 중서부 (Midwest)
    'IL': 'Midwest', 'IN': 'Midwest', 'MI': 'Midwest', 'OH': 'Midwest', 'WI': 'Midwest', 'IA': 'Midwest', 'KS': 'Midwest', 'MN': 'Midwest', 'MO': 'Midwest', 'NE': 'Midwest', 'ND': 'Midwest', 'SD': 'Midwest',
    # 남부 (South)
    'DE': 'South', 'FL': 'South', 'GA': 'South', 'MD': 'South', 'NC': 'South', 'SC': 'South', 'VA': 'South', 'DC': 'South', 'WV': 'South', 'AL': 'South', 'KY': 'South', 'MS': 'South', 'TN': 'South', 'AR': 'South', 'LA': 'South', 'OK': 'South', 'TX': 'South',
    # 서부 (West)
    'AZ': 'West', 'CO': 'West', 'ID': 'West', 'MT': 'West', 'NV': 'West', 'NM': 'West', 'UT': 'West', 'WY': 'West', 'AK': 'West', 'CA': 'West', 'HI': 'West', 'OR': 'West', 'WA': 'West'
}

# 카드 소유자 거주지(CARD_HOLDER_STATE) 기준으로 REGION 칼럼 추가
df['REGION'] = df['CARD_HOLDER_STATE'].map(state_to_region).fillna('Unknown')

In [ ]:
import pandas as pd

# 데이터프레임 이름이 'df'라고 가정합니다.
# 결측치나 공백 제거 등 기본 전처리가 되어있다고 가정합니다.

# ==========================================
# 1. 지역별 업종(카테고리) 소비 비중 비교
# ==========================================
# 각 지역 내에서 특정 카테고리가 차지하는 비중(%)을 계산합니다.
category_ratio = pd.crosstab(
    index=df['MERCHANT_CATEGORY_LEVEL_3'], 
    columns=df['REGION'], 
    normalize='columns' # 열(지역) 기준으로 100%가 되도록 정규화
) * 100

# 보기 편하게 소수점 둘째 자리까지 반올림
category_ratio = category_ratio.round(2)

print("--- 지역별 업종 비중(%) ---")
display(category_ratio)


# ==========================================
# 2. 지역별 가맹점 이름 소비 비중 비교 (전체)
# ==========================================
merchant_ratio = pd.crosstab(
    index=df['MERCHANT_NAME'], 
    columns=df['REGION'], 
    normalize='columns'
) * 100

merchant_ratio = merchant_ratio.round(2)


# ==========================================
# 3. [추천] 각 지역별 TOP 10 가맹점 비중 추출
# ==========================================
# 전체 가맹점을 보면 표가 너무 길어지므로, 지역별로 가장 많이 소비한 TOP 10만 뽑아냅니다.
def get_top_merchants(group, top_n=10):
    # 그룹(지역) 내 비중 계산
    ratios = group.value_counts(normalize=True) * 100
    # 상위 N개 반환
    return ratios.nlargest(top_n).round(2)

# REGION으로 그룹화한 뒤 MERCHANT_NAME 단위로 함수 적용
top_merchants_by_region = df.groupby('REGION')['MERCHANT_NAME'].apply(get_top_merchants)

# 결과를 데이터프레임 형태로 깔끔하게 변환
top_merchants_df = top_merchants_by_region.reset_index()
top_merchants_df.columns = ['REGION', 'MERCHANT_NAME', 'RATIO(%)']

print("\n--- 지역별 TOP 10 가맹점 비중(%) ---")
display(top_merchants_df)

--- 지역별 업종 비중(%) ---

REGION                              Midwest  Northeast  South  Unknown  West
MERCHANT_CATEGORY_LEVEL_3
Airline Travel                         0.02       0.03   0.02     0.05  0.06
American Restaurants                   6.13       2.85   3.75     5.73  3.02
Amusement Parks                        0.09       0.20   0.29     0.37  0.29
Apparel, Accessories, and Footwear     0.00       0.00   0.00     0.01  0.01
Arcades                                0.00       0.00   0.00     0.00  0.00
...                                     ...        ...    ...      ...   ...
Upscale Hotels                         0.00       0.00   0.00     0.00  0.00
Vending & Beverage Retailers          14.16      10.23  11.68     8.33  9.13
Video Game Retail and Streaming        0.00       0.00   0.00     0.00  0.00
Wireless Services                      0.00       0.00   0.00     0.00  0.00
Women's Apparel                        0.00       0.00   0.00     0.00  0.01

[87 rows x 5 columns]

--- 지역별 TOP 10 가맹점 비중(%) ---

       REGION       MERCHANT_NAME  RATIO(%)
0     Midwest           MCDONALDS     18.55
1     Midwest           NO ENTITY     18.33
2     Midwest           STARBUCKS      5.34
3     Midwest  365 RETAIL MARKETS      4.95
4     Midwest           TACO BELL      4.81
5     Midwest              WENDYS      3.69
6     Midwest       DUNKIN DONUTS      3.15
7     Midwest         BURGER KING      3.05
8     Midwest         CHICK-FIL-A      2.60
9     Midwest            CHIPOTLE      2.49
10  Northeast           NO ENTITY     24.29
11  Northeast           MCDONALDS     15.45
12  Northeast       DUNKIN DONUTS     14.81
13  Northeast           STARBUCKS      6.24
14  Northeast              WENDYS      3.81
15  Northeast         BURGER KING      3.72
16  Northeast         CHICK-FIL-A      3.09
17  Northeast  365 RETAIL MARKETS      2.99
18  Northeast           TACO BELL      2.35
19  Northeast            CHIPOTLE      2.31
20      South           NO ENTITY     19.45
21      South           MCDONALDS     14.56
22      South         CHICK-FIL-A      7.33
23      South           STARBUCKS      5.36
24      South  365 RETAIL MARKETS      4.03
25      South           TACO BELL      3.27
26      South              WENDYS      3.21
27      South       DUNKIN DONUTS      2.75
28      South      SONIC DRIVE-IN      2.64
29      South         BURGER KING      2.57
30    Unknown           NO ENTITY     30.55
31    Unknown           MCDONALDS     12.99
32    Unknown           STARBUCKS      5.18
33    Unknown         BURGER KING      4.67
34    Unknown              WENDYS      4.67
35    Unknown         CHICK-FIL-A      3.32
36    Unknown           TACO BELL      2.71
37    Unknown              SUBWAY      2.65
38    Unknown  365 RETAIL MARKETS      2.42
39    Unknown     CHURCHS CHICKEN      2.05
40       West           NO ENTITY     27.59
41       West           MCDONALDS     13.95
42       West           STARBUCKS      9.47
43       West           TACO BELL      3.66
44       West         CHICK-FIL-A      3.09
45       West              WENDYS      2.66
46       West  DUTCH BROS. COFFEE      2.41
47       West     JACK IN THE BOX      2.35
48       West       PANDA EXPRESS      2.17
49       West  365 RETAIL MARKETS      2.04

In [ ]:
import pandas as pd

# df는 현재 사용 중인 데이터프레임 이름이라고 가정합니다.

# REGION과 CLUSTER_K4를 다중 인덱스(행)로 설정하고, 열을 CARD_TYPE으로 지정합니다.
card_type_ratio = pd.crosstab(
    index=[df['REGION'], df['CLUSTER_K4']], 
    columns=df['CARD_TYPE'], 
    normalize='index' # 각 그룹(지역+군집)의 합이 100%가 되도록 가로 방향 정규화
) * 100

# 보기 편하게 소수점 둘째 자리까지 반올림
card_type_ratio = card_type_ratio.round(2)

print("--- REGION별 & CLUSTER_K4별 CARD_TYPE 비율(%) ---")
display(card_type_ratio)

--- REGION별 & CLUSTER_K4별 CARD_TYPE 비율(%) ---

CARD_TYPE             Benefit - Health  Credit  Debit  General Purpose  \
REGION    CLUSTER_K4
Midwest   0                       0.00   26.32  73.67             0.00
          1                       0.00    6.66  93.22             0.04
          2                       0.00   11.57  88.30             0.12
          3                       0.00   11.65  88.24             0.06
Northeast 0                       0.00   42.08  57.92             0.00
          1                       0.00   16.60  83.08             0.14
          2                       0.00   21.21  78.54             0.25
          3                       0.00   26.30  73.43             0.17
South     0                       0.00   56.71  43.29             0.00
          1                       0.00   13.60  86.21             0.04
          2                       0.00   18.95  80.89             0.15
          3                       0.00   21.20  78.65             0.06
Unknown   0                       0.04   94.95   5.00             0.00
          1                       0.79   15.41  83.23             0.01
          2                       0.00   51.68  46.71             0.00
          3                       0.15   23.22  76.08             0.01
West      0                       0.00   47.58  52.42             0.00
          1                       0.00   28.63  71.22             0.03
          2                       0.00   34.97  64.91             0.11
          3                       0.00   40.18  59.69             0.06

CARD_TYPE             Payroll
REGION    CLUSTER_K4
Midwest   0              0.00
          1              0.08
          2              0.00
          3              0.06
Northeast 0              0.00
          1              0.18
          2              0.01
          3              0.10
South     0              0.00
          1              0.15
          2              0.01
          3              0.08
Unknown   0              0.00
          1              0.56
          2              1.61
          3              0.53
West      0              0.00
          1              0.12
          2              0.00
          3              0.07

In [ ]:
import pandas as pd

# df는 현재 사용 중인 데이터프레임 이름이라고 가정합니다.

# 1. 군집별 전체 카드 타입 결제 비율(%) 계산
card_ratio_by_cluster = pd.crosstab(
    index=df['CLUSTER_K4'], 
    columns=df['CARD_TYPE'], 
    normalize='index' # 각 군집의 총 결제 건수를 100%로 두고 정규화
) * 100

# 소수점 둘째 자리까지 반올림
card_ratio_by_cluster = card_ratio_by_cluster.round(2)

print("--- 군집별 전체 카드 타입 비율(%) ---")
display(card_ratio_by_cluster)

# 2. 신용카드(Credit) 비율만 추출해서 보기
# 만약 데이터의 값이 대소문자가 다르다면(예: 'credit') 그에 맞게 수정해 주세요.
if 'Credit' in card_ratio_by_cluster.columns:
    credit_ratio = card_ratio_by_cluster[['Credit']]
    print("\n--- 군집별 신용카드(Credit) 집중 분석(%) ---")
    display(credit_ratio)
else:
    print("\n'Credit' 컬럼이 존재하지 않습니다. CARD_TYPE의 실제 고유값들을 확인해 주세요.")

--- 군집별 전체 카드 타입 비율(%) ---

CARD_TYPE   Benefit - Health  Credit  Debit  General Purpose  Payroll
CLUSTER_K4
0                        0.0   45.23  54.77             0.00     0.00
1                        0.0   13.80  86.02             0.04     0.13
2                        0.0   19.70  80.15             0.14     0.01
3                        0.0   22.17  77.68             0.07     0.08

--- 군집별 신용카드(Credit) 집중 분석(%) ---

CARD_TYPE   Credit
CLUSTER_K4
0            45.23
1            13.80
2            19.70
3            22.17